[Output]
ImageId=webthings-gateway
Format=disk
SplitArtifacts=uki,partitions
ManifestFormat=json
Output=%i_%v_%a


[Distribution]
Distribution=debian
Release=trixie
Repositories=non-free-firmware


[Content]
Packages=
        auditd
        bpftool
        ca-certificates
        cryptsetup-bin
        debian-archive-keyring
        iproute2
        iputils-ping
        libcap-ng-utils
        libidn2-0
        libnss-myhostname
        libnss-mymachines
        libnss-systemd
        libpam-pwquality
        libpam-systemd
        libpwquality1
        libqrencode4
        linux-image-generic
        firmware-sof-signed
        linux-sysctl-defaults
        locales
        login
        polkitd
        procps
        systemd-boot
        systemd-boot-efi
        systemd-cryptsetup
        systemd-coredump
        systemd-resolved
        systemd-repart
        systemd-zram-generator
        tpm2-tools
        util-linux-extra
        plymouth-themes
        # This is for gateway
        modemmanager
        network-manager
        net-tools
        avahi-daemon
        mosquitto
        chrony
        iw
        arping
        nodejs
        python3
        python3-six
        ffmpeg

BuildPackages=
        build-essential
        git
        rsync
        python3-pip
        pipx
        python3-setuptools
        python-is-python3
        npm
        pkg-config
        libdbus-1-dev

WithDocs=no
WithRecommends=no

# Set defaults for systemd-firstboot that we override during setup
Locale=en_US.utf8
Keymap=us
Timezone=UTC
RootShell=/usr/bin/bash

# This is just a transient hostname
Hostname=gateway

# mkosi installs a helper SSH socket to allow local host/VM connection,
# don't enable this by default and only in the VM profile.
Ssh=never

# Mark the image as bootable, but we set what bootloader to use (ie systemd-boot or grub) per architecture
Bootable=yes
Bootloader=systemd-boot

# TODO: Edit /usr/lib/os-release to use "WebThings Gateway" for ID as this is used in creating the UKI
KernelCommandLine=
        rw
        quiet
        splash

# Include our own initrd so that plymouth uses the correct splash
Initrds=%O/webthings-initrd-%v.cpio.zst

# Unset any initrd profiles
InitrdProfiles=


[Validation]
SecureBoot=yes
SignExpectedPcr=yes
Verity=yes
Checksum=yes


[Config]
# We need to build our initrd first, then we can add it to our UKIs
Dependencies=webthings-initrd


[Build]
ToolsTree=default
# We need to force debian trixie as mkosi defaults to testing
ToolsTreeDistribution=debian
ToolsTreeRelease=trixie
# Include devel tooling like git, make etc
ToolsTreeProfiles=misc,runtime,devel
CacheDirectory=mkosi.cache
Incremental=yes
WithNetwork=yes
# Mount the git checkout into mkosi for building
BuildSources=../:gateway
