[Partition]
Type=usr
Label=webthings_gw_%A

Format=erofs
Minimize=yes
Compression=zstd
SizeMaxBytes=2G
SplitName=%t.%U

CopyFiles=/usr:/

# This will ensure the image is correct and genuine
Verity=data
VerityMatchKey=usr
