# Include vm to log in
[Include]
Include=mkosi-vm

[Content]
Packages=
        openssh-server

RootPassword=password
Ssh=auto

[Build]
# Include the runtime profile for QEMU support
## This needs to include whatever is in the main mkosi.conf file as the profile config overrides it.
ToolsTreeProfiles=misc,runtime

[Runtime]
TPM=yes
Ephemeral=yes
RuntimeSize=10G
